=== gaelgael5/galileo/src/ApplicationCooperationViewPoint/Debugging/Schemas/CooperationViewpoint.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://Pickup.fr/carto/schemas/CooperationViewpoint",
  "title": "CooperationViewpoint",
  "type": "object",
  "required": [
    "Name"
  ],
  "properties": {
    "Name": {
      "type": "string"
    },
    "Concepts": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/CooperationConcept"
      }
    },
    "Elements": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/CooperationRootElement"
      }
    },
    "References": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "#/definitions/CooperationRelationship"
      }
    }
  },
  "definitions": {
    "CooperationConcept": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Name"
      ],
      "properties": {
        "Name": {
          "type": "string",
          "enum": [
            "DomainConcept",
            "Application",
            "ModuleApplication",
            "Producer",
            "DataObject"
          ]
        },
        "Children": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/CooperationElement"
          }
        }
      }
    },
    "CooperationElement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Name"
      ],
      "properties": {
        "Name": {
          "type": "string",
          "enum": [
            "ConceptHasApplication",
            "ApplicationHasModule",
            "ProducerProductData"
          ]
        },
        "Children": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/CooperationRelationship"
          }
        }
      }
    },
    "CooperationRelationship": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Name"
      ],
      "properties": {
        "Name": {
          "type": "string",
          "enum": [
            "ConceptHasApplication",
            "ApplicationHasModule",
            "ProducerProductData"
          ]
        }
      }
    },
    "CooperationRootElement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Name"
      ],
      "properties": {
        "Name": {
          "type": "string",
          "enum": [
            "DomainConcept",
            "Application",
            "ModuleApplication",
            "Producer",
            "DataObject"
          ]
        },
        "Children": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/CooperationRelationship"
          }
        }
      }
    }
  }
}

=== gaelgael5/galileo/src/ApplicationCooperationViewPoint/Debugging/definitions/Applicative.cooperationview.defs.json
{

    "$schema": "..\\Schemas\\CooperationViewpoint.schema.json",

    "Name": "Applicative viewpoint",

    "Concepts": [
        {
            "Name": "DomainConcept",
            "Children": [
                {
                    "Name": "ConceptHasApplication",
                    "Children": [
                        {
                            "Name": "ApplicationHasModule"
                        }
                    ]
                }
            ]

        }
    ],
    "Elements": [
        {
            "Name": "Application",
            "Children": [
                {
                    "Name":  "ApplicationHasModule"
                }
            ]
        }
    ],
    "References": [
       
    ]

}
